# Generated by Django 3.0.8 on 2020-07-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20200704_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('BK', 'Berkeley'), ('OAK', 'Oakland'), ('NY', 'New York'), ('SF', 'San Francisco'), ('SJ', 'San Jose'), ('LA', 'Los Angeles')], max_length=50),
        ),
    ]
