# Generated by Django 3.0.8 on 2020-07-04 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20200704_0356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salehistory',
            name='user',
        ),
    ]
